//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rankings.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rankings.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appends a set of contest results from a file into the results file..
        /// </summary>
        internal static string AppendFile_Subcommand_Description {
            get {
                return ResourceManager.GetString("AppendFile_Subcommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file specified cannot be accessed. The file name and path may be incorrect, the file may not be accessible, or the file may not exist..
        /// </summary>
        internal static string AppendFile_Subcommand_FileNotAccessible {
            get {
                return ResourceManager.GetString("AppendFile_Subcommand_FileNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appends a single contest result to the results file..
        /// </summary>
        internal static string AppendResult_Subcommand_Description {
            get {
                return ResourceManager.GetString("AppendResult_Subcommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot contain a new line..
        /// </summary>
        internal static string CannotContainNewLine {
            get {
                return ResourceManager.GetString("CannotContainNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears contest results from the contest results store..
        /// </summary>
        internal static string ClearContestResults_Subcommand_Description {
            get {
                return ResourceManager.GetString("ClearContestResults_Subcommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot generate a valid contest result from invalid input..
        /// </summary>
        internal static string ContestResultParser_Validation_InvalidStateForGeneration {
            get {
                return ResourceManager.GetString("ContestResultParser_Validation_InvalidStateForGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A result must be separated into two parts by the {0} symbol; one part for each contestant&apos;s name and score..
        /// </summary>
        internal static string ContestResultParser_Validation_MissingContestantResultSeparator {
            get {
                return ResourceManager.GetString("ContestResultParser_Validation_MissingContestantResultSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A result can only contain one {0} symbol..
        /// </summary>
        internal static string ContestResultParser_Validation_MultipleContestantResultSeparators {
            get {
                return ResourceManager.GetString("ContestResultParser_Validation_MultipleContestantResultSeparators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A result must not contain any line breaks, it must be a single line..
        /// </summary>
        internal static string ContestResultParser_Validation_NewLineWithinContestantResult {
            get {
                return ResourceManager.GetString("ContestResultParser_Validation_NewLineWithinContestantResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A result must include names for both contestants. Cannot find a name for contestant {0}..
        /// </summary>
        internal static string ContestResultParser_Validation_NoContestantName {
            get {
                return ResourceManager.GetString("ContestResultParser_Validation_NoContestantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A result must include the results for both contestants. Cannot find a result for contestant {0}..
        /// </summary>
        internal static string ContestResultParser_Validation_NoContestantResult {
            get {
                return ResourceManager.GetString("ContestResultParser_Validation_NoContestantResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A result must include scores for both contestants. Cannot find a score for contestant {0}..
        /// </summary>
        internal static string ContestResultParser_Validation_NoContestantScore {
            get {
                return ResourceManager.GetString("ContestResultParser_Validation_NoContestantScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success: The contest results store has been cleared..
        /// </summary>
        internal static string ContestResultsProcessor_Clear_Success {
            get {
                return ResourceManager.GetString("ContestResultsProcessor_Clear_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot display the ranking table because no results exist in the contest results store. Please add results, then retry..
        /// </summary>
        internal static string ContestResultsProcessor_Display_NoData {
            get {
                return ResourceManager.GetString("ContestResultsProcessor_Display_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. {1}, {2} {3}.
        /// </summary>
        internal static string ContestResultsProcessor_DisplayRankingTable_Row {
            get {
                return ResourceManager.GetString("ContestResultsProcessor_DisplayRankingTable_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error: The contest results processor is not registered..
        /// </summary>
        internal static string ContestResultsProcessor_NotRegistered {
            get {
                return ResourceManager.GetString("ContestResultsProcessor_NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success: Added {0} contest result(s) to the contest results store. Rerun the command without any arguments to see the rankings latest table..
        /// </summary>
        internal static string ContestResultsProcessor_Processing_Success {
            get {
                return ResourceManager.GetString("ContestResultsProcessor_Processing_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current ranking is:.
        /// </summary>
        internal static string ContestResultsProcessor_RankingDisplay_Header {
            get {
                return ResourceManager.GetString("ContestResultsProcessor_RankingDisplay_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pts.
        /// </summary>
        internal static string ContestResultsProcessor_RankingDisplay_PointPlural {
            get {
                return ResourceManager.GetString("ContestResultsProcessor_RankingDisplay_PointPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pt.
        /// </summary>
        internal static string ContestResultsProcessor_RankingDisplay_PointSingular {
            get {
                return ResourceManager.GetString("ContestResultsProcessor_RankingDisplay_PointSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in contestant result {0}: .
        /// </summary>
        internal static string ContestResultsProcessor_Validation_ParsingError {
            get {
                return ResourceManager.GetString("ContestResultsProcessor_Validation_ParsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty or white-space..
        /// </summary>
        internal static string EmptyOrWhiteSpace {
            get {
                return ResourceManager.GetString("EmptyOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports a set of contest results from the specified file into the results file. Each result must be in the form: &quot;&lt;CONTESTANT-1&gt; &lt;SCORE-1&gt;, &lt;CONTESTANT-2&gt; &lt;SCORE-2&gt;&quot;. See help for the append-result command for further information..
        /// </summary>
        internal static string FileOption_Description {
            get {
                return ResourceManager.GetString("FileOption_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory (folder) name contains invalid characters and is invalid..
        /// </summary>
        internal static string FileOption_Validation_InvalidDirectoryName {
            get {
                return ResourceManager.GetString("FileOption_Validation_InvalidDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name contains invalid characters and is invalid..
        /// </summary>
        internal static string FileOption_Validation_InvalidFileName {
            get {
                return ResourceManager.GetString("FileOption_Validation_InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name is missing or empty..
        /// </summary>
        internal static string FileOption_Validation_MissingFileName {
            get {
                return ResourceManager.GetString("FileOption_Validation_MissingFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a single contest result to the results file. A result must be in the form: &quot;&lt;CONTESTANT-1&gt; &lt;SCORE-1&gt;, &lt;CONTESTANT-2&gt; &lt;SCORE-2&gt;&quot;. Replace &lt;CONTESTANT-n&gt; with the contestants&apos; names such as, Team One, Team Two, etc. Names cannot start with - or --, and they cannot include the {0} symbol. Scores must be non-negative, whole numbers without any separator symbols, which means for example that 1000 is appropriate but 1,000 is not. Example: rankings -r &quot;My Team 1{0} Other Team 0&quot;.
        /// </summary>
        internal static string ResultOption_Description {
            get {
                return ResourceManager.GetString("ResultOption_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a ranking table..
        /// </summary>
        internal static string RootCommand_Description {
            get {
                return ResourceManager.GetString("RootCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error: The storage factory is not registered..
        /// </summary>
        internal static string StorageFactory_NotRegistered {
            get {
                return ResourceManager.GetString("StorageFactory_NotRegistered", resourceCulture);
            }
        }
    }
}
